apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: impactlens
  description: Tool to evaluate ai impacts for team and individuals productivity
  annotations:
    github.com/project-slug: testcara/impactlens
spec:
  type: service
  lifecycle: production
  owner: user:default/testcara
