apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: konflux-ui
  description: UI for konflux deliverly tool
  annotations:
    github.com/project-slug: konflux-ci/konflux-ui
    jira/project-key: KFLUXUI
spec:
  type: service
  lifecycle: production
  owner: group:default/konflux-ui
  system: konflux-ui
